[package]
name = "claw-lang"
version = "0.1.0"
authors = ["Arc-blroth <45273859+Arc-blroth@users.noreply.github.com>"]
edition = "2018"

[dependencies]
heck = "0.3.1"
strum = "0.19"
strum_macros = "0.19"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"